[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
auto_detect_solc = true
optimizer = true
optimizer_runs = 10

[profile.test]
no_match_test = "Fuzzing"
no_match_contract = "Fuzzing"
gas_reports = ["ZenBullNetting"]

[profile.fuzz]
runs = 2500
max_local_rejects = 1024
max_global_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
match_test = "Fuzzing"
match_contract = "Fuzzing"

[profile.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[profile.coverage]
via_ir = true
no_match_test = "Fuzzing"
no_match_contract = "Script"

[profile.coverage.optimizer_details]
constantOptimizer = true
yul = true

[profile.coverage.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = ''

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config