name: Founry

on: [push]

jobs:
  check:
    name: Forge lints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run fmt
        run: cd packages/bull-vault && forge fmt